//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contact_Billing_XamarinService.DataObjects
{
    using Microsoft.Azure.Mobile.Server;
    using System;
    using System.Collections.Generic;
    
    public partial class Call : EntityData
    {
        public int User_ID { get; set; }
        public int Contact_ID { get; set; }
        public byte[] Start_Time { get; set; }
        public int Duration { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Amt_Billed { get; set; }
        public string Note { get; set; }
    
        public virtual Contact Contact { get; set; }
        public virtual User User { get; set; }
    }
}
