//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contact_Billing_XamarinService.DataObjects
{
    using Microsoft.Azure.Mobile.Server;
    using System;
    using System.Collections.Generic;
    
    public partial class Project : EntityData
    {
        public int Project_ID { get; set; }
        public int Contact_ID { get; set; }
        public string Username { get; set; }
        public System.DateTime Date_Started { get; set; }
        public decimal Billed_Total { get; set; }
    }
}
